# Generated by Django 3.0.2 on 2020-01-29 18:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fieldParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.FloatField(max_length=256)),
                ('rainfall', models.FloatField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 14, 123979, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid1', models.FloatField(max_length=256)),
                ('grid2', models.FloatField(max_length=256)),
                ('grid3', models.FloatField(max_length=256)),
                ('grid4', models.FloatField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 14, 123145, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidty', models.FloatField(max_length=256)),
                ('temperature', models.FloatField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 14, 123567, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 14, 122565, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
