# Generated by Django 3.0.2 on 2020-01-29 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 56, 87260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 56, 86434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 56, 85881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 11, 56, 86872, tzinfo=utc)),
        ),
    ]
