# Generated by Django 3.0.2 on 2020-01-29 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200129_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 12, 5, 204111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 12, 5, 203283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 12, 5, 202735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 12, 5, 203704, tzinfo=utc)),
        ),
    ]
