# Generated by Django 3.0.2 on 2020-01-29 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200129_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 29, 11, 48094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 29, 11, 47274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 29, 11, 46735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 29, 11, 47697, tzinfo=utc)),
        ),
    ]
