# Generated by Django 3.0.2 on 2020-02-01 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200201_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 12, 32, 14, 40128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 12, 32, 14, 39338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 12, 32, 14, 38806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 12, 32, 14, 39750, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintxn', models.CharField(default='COMP123', max_length=256)),
                ('complain', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 2, 1, 12, 32, 14, 40558, tzinfo=utc))),
                ('complainid', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=0)),
                ('username', models.CharField(default='USER1', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
