# Generated by Django 3.0.2 on 2020-02-02 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200201_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 18, 50, 56, 438560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 18, 50, 56, 438104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 18, 50, 56, 437171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 18, 50, 56, 436444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 18, 50, 56, 437640, tzinfo=utc)),
        ),
    ]
